version: '3'
services:
  nest-authentication-ytb-db:
    container_name: nest-authentication-ytb-db
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_authentication_ytb
      port: 5432